### ISSUE TITLE
More date sources

### ISSUE THREAD

**Issue by PrincesseLulu** [sidharthrajaram/nbaszn#1]
Hi,

First, thank you for your work, is it a very good project !

I'd like to add more date sources i see it's in team_scraper.py

```def getTeamStats(team_id):
    team = team_id.upper()
url = "https://www.basketball-reference.com/teams/" + team + "/2019.html"```

I think it's more precise if you have more date, because in 2019 we have only 2 month past.
I want to scrap 2018 and 2019 years, it's possible to edit easily your code for it ?

Thank you !

**Comment by sidharthrajaram** [comment]
Great idea! Feel free to fork it and add your improvements.

**Comment by sidharthrajaram** [comment]
In my latest commit, the scraping now includes a parameter for the year of the team. This means you can scrape for team data from any year.

**Comment by PrincesseLulu** [comment]
Oh it's good! I look it now.
They are long time have not use your script becose i'v not to mush time actually. 

Your win stat is good? I think I retry it soon! 
Did you need help for some functionality? A to-do list? 

I'v dev' à web ui with nodejs language for use your script without command. Maybe I can adapt it and share it? 

Lulu
