### ISSUE TITLE
Feature: Connect to Betfair

### ISSUE THREAD

**Issue by zbanga** [sidharthrajaram/nbaszn#2]
Hi,

Would you be interested in connecting to Betfair and automating the betting(paper)?

Would be an interesting exercise!

**Comment by sidharthrajaram** [comment]
Hey, that sounds pretty intriguing. 😲 Can you tell me more about what you have in mind?

**Comment by zbanga** [comment]
I was thinking to backtest the predictions and see if they have an edge over Betfair prices. And if they did try with paper trading it. 
So pretty much download closing odds from Betfair and then determine over the season there is any profit.

**Comment by sidharthrajaram** [comment]
Oh, got it. Is Betfair the most notable provider of closing odds or are there other providers as well?

**Comment by zbanga** [comment]
There are other sites but they don't have API connectivity like Betfair does
And it would make it easier to backtest the odds on the exchange we are using

**Comment by PrincesseLulu** [comment]
Hi, Betfair isn't available in my contry.
But i work on the same idea with an other site.
If i do it i tell you ;)

**Comment by sidharthrajaram** [comment]
Sounds great! It should be able to work with any website with betting data.

**Comment by PrincesseLulu** [comment]
Yeap but need to code differents integration for all website.. Becose it's haven't the same structure or Api.
But I dev' a web ui for manage my bets and prediction. So maybe I can dev 'a plug-in system for integration easy? 
To be continued 😁

**Comment by PrincesseLulu** [comment]
Yeap but need to code differents integration for all website.. Becose it's haven't the same structure or Api.
But I dev' a web ui for manage my bets and prediction. So maybe I can dev 'a plug-in system for integration easy? 
............................... 

Technically you need: 
- a script that retrieves the games of the day via an api nba 
- a script that makes the predictions
- an integration of bets sites 
- a script that retrieves the results of the matches 
- a script that recovers the winnings money

And I'm looking to do all that's with a simple web ui
