### ISSUE TITLE
Need somes info

### ISSUE THREAD

**Issue by PrincesseLulu** [sidharthrajaram/nbaszn#3]
Hey,

I'v fork the project and i'm looking for work on ;)
Actually i haven't my computer so i can't look python version needing.
Can you give me library and python version you use on master and lib infos ?
I'm looking for create docker adapatation (and i pull it on your project ;) )

**Comment by sidharthrajaram** [comment]
Hey, sorry for the late response.
I believe the dependencies are:

1. python 3
2. matplotlib
3. numpy
4. pandas
5. beautiful soup 4
6. urllib3
7. requests

**Comment by sidharthrajaram** [comment]
Here is how the import statements look like:
```
import requests
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
import re
import urllib.request
```

**Comment by PrincesseLulu** [comment]
Oh thanks ! No problem for the late response ;)
When i does it, i will to create a pull request ;)
