### ISSUE TITLE
How can i run script

### ISSUE THREAD

**Issue by eaavilas** [sidharthrajaram/nbaszn#4]
Hi sidhart,
how are you?
i have a question
How can i run script?, but i dont know that script i should run.

**Comment by sidharthrajaram** [comment]
Hi there, great question!
Try running **game_improved.py** (using python 3). 
On my machine I just go to the project folder in terminal and do `python3 game_improved.py`

**Comment by PrincesseLulu** [comment]
@sidharthrajaram can you add a feature for run script like this "python3 game_improved.py {TEAM_HOME} {TEAM_AWAY}".
For win in time and run it more easy (just add argument to script). If you do that's please add it too in "game_basic.py". Thanks

**Comment by sidharthrajaram** [comment]
Yeah, that's a great idea. I'll add it soon.

**Comment by sidharthrajaram** [comment]
Just wanted to update, the latest script can be run this way.
`python predict_game.py {YEAR} {HOME_TEAM} {YEAR} {AWAY_TEAM}`
Thanks for the suggestion.
