### ISSUE TITLE
trouble running

### ISSUE THREAD

**Issue by VigilantOne2119** [sidharthrajaram/nbaszn#6]
Hi, im not able to run this as i keep getting the error: Traceback (most recent call last):
  File "C:/Users/risin/OneDrive/Documents/GitHub/CrystalBall/predict_game.py", line 6, in <module>
    simulate_game(sys.argv[1], sys.argv[3], sys.argv[2], sys.argv[4], display_info=True)
IndexError: list index out of range

**Comment by sidharthrajaram** [comment]
Hey @VigilantOne2119 , did you try running the script like this:
`python3 predict_game.py <home_year> <home_team_id> <away_year> <away_team_id>` ?

For example:
<img width="722" alt="Screen Shot 2021-02-15 at 9 29 43 PM" src="https://user-images.githubusercontent.com/14987538/108022246-0bb41300-6fd5-11eb-9df8-0c4f1e6f543e.png">

**Comment by VigilantOne2119** [comment]
I have tried that. when i do that it gives me  File "predict_game.py", line 1, in <module>
    from sim import simulate_game
  File "C:\Users\risin\OneDrive\Documents\GitHub\CrystalBall\sim.py", line 1, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'

I have installed seaborn so i cant find a solution. 

Thanks for the reply by the way!

**Comment by sidharthrajaram** [comment]
Hey @VigilantOne2119, interesting. Are you sure your pip version (used to install seaboard) and the python version (used to run sim.py) are the same? Also, are you using a virtual environment?

**Comment by sidharthrajaram** [comment]
Closed it but feel free to respond if the problem still persists, and I can reopen!
